version: '3'
services:
        #Database Service Oluşturuyoruz
        db:
                image: mysql:5.7
                volumes:
                        - db_data:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: cokgizlisifre
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: sezerkahraman
                        MYSQL_PASSWORD: birikiuc
                networks:
                        - sw-br-networks
        #Wordpress Service Oluşturuyoruz
        wordpress:
                depends_on:
                        - db
                image: wordpress:latest
                ports:
                        - "8080:80"
                restart: always
                volumes:
                        - /var/www/html
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: sezerkahraman
                        WORDPRESS_DB_PASSWORD: birikiuc
                networks:
                        - sw-br-networks
        #phpMyAdmin Service Oluşturuyoruz
        phpmyadmin:
                depends_on:
                        - db
                image: phpmyadmin/phpmyadmin
                restart: always
                ports:
                        - "7080:80"
                environment:
                        PMA_HOST: db
                        MYSQL_ROOT_PASSWORD: cokgizlisifre
                networks:
                        - sw-br-networks
networks:
        sw-br-networks:
volumes:
        db_data:







